# Generated by Django 5.2.9 on 2026-01-01 05:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_useridentity'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('END_USER', 'End User'), ('STAFF', 'Staff'), ('SYSTEM_ADMIN', 'System Admin'), ('DATA_ADMIN', 'Data Admin')], default='END_USER', max_length=20),
        ),
        migrations.CreateModel(
            name='UserRolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('END_USER', 'End User'), ('STAFF', 'Staff'), ('SYSTEM_ADMIN', 'System Admin'), ('DATA_ADMIN', 'Data Admin')], max_length=30)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userpermission')),
            ],
            options={
                'unique_together': {('role', 'permission')},
            },
        ),
    ]
